- .gitignore
- project.clj
- src/clj/puppetlabs/http/client/async.clj
- src/java/com/puppetlabs/http/client/impl/SslUtils.java
- test/puppetlabs/http/client/async_ssl_config_test.clj
This changes the usages to reflect the new name of the library and API.
This also contains upgrades for the clj-kitchensink and trapperkeeper to bring them up to the newest releases and in line with the versions used in puppet server.
> (SERVER-101) Update jvm-ca dependency

- dev-resources/java.security
- ext/travisci/test.sh
- project.clj
Also, make our TravisCI file more robust so it doesn't bite us in the future.
I made the same changes that we did in Puppet Server: https://github.com/puppetlabs/puppet-server/pull/382
I wasn't quite sure about whether the documentation was necessary or not so I left it out.
Happy to add some if it's worthwhile.
> (TK-143) Allow SSLv3 in tests

- .gitignore
- project.clj
- src/clj/puppetlabs/http/client/async.clj
- src/java/com/puppetlabs/http/client/impl/JavaClient.java
- test/com/puppetlabs/http/client/impl/java_client_test.clj
- test/puppetlabs/http/client/async_test.clj
Fix a bug in which a default charset of UTF-8 would be added to the
Content-Type header for certain requests.  This change restricts that
behavior to cases in which the body is a string and there is no charset
provided by the caller.
@cprice404 @camlow325 If you two fine gentlemen would please review this, that'd be swell.
> (TK-145) fix application of default charset

- doc/clojure-client.md
- project.clj
- src/clj/puppetlabs/http/client/async.clj
- src/clj/puppetlabs/http/client/common.clj
- src/clj/puppetlabs/http/client/sync.clj
- src/java/com/puppetlabs/http/client/ClientOptions.java
- src/java/com/puppetlabs/http/client/SimpleRequestOptions.java
- src/java/com/puppetlabs/http/client/Sync.java
- src/java/com/puppetlabs/http/client/impl/CoercedClientOptions.java
- src/java/com/puppetlabs/http/client/impl/JavaClient.java
- test/puppetlabs/http/client/async_plaintext_test.clj
- test/puppetlabs/http/client/sync_plaintext_test.clj
- test/puppetlabs/http/client/test_common.clj
This commit enables http clients to optionally configure a connect
and/or socket timeout for requests.  For persistent clients, the
timeout values can only be configured at the client and not a
per-request level.  Non-persistent client requests support the
configuration of these timeouts.
This commit also bumps a few dependencies - tk-jetty9 to 1.2.0,
trapperkeeper to 1.10, ssl-utils to 0.8.0, and clojure to 1.6.0 -
and adds the 'test' tk-jetty9 library as a dev dependency for
testing.
> (TK-134) Add connect and socket timeout client configuration

- test/puppetlabs/http/client/async_plaintext_test.clj
- test/puppetlabs/http/client/sync_plaintext_test.clj
This commit has a couple of cosmetic fixes to the names and testing
strings for a few tests introduced by TK-134.
> (MAINT) Fix timeout test names and testing strings

- project.clj
- src/clj/puppetlabs/http/client/async.clj
- src/clj/puppetlabs/http/client/sync.clj
The prismatic/plumbing and prismatic/schema library dependencies are
lagging behind the latest stable version. This will increasingly
cause conflicts in trapperkeeper projects. This patch updates the
dependencies and fixes several functions which were validating against
schemas incompatible with the new versions.
* Update project.clj dependencies
* Use protocol schema instead of the protocol object directly
> (TK-196) Update prismatic library dependencies

- .gitignore
- doc/clojure-client.md
- src/clj/puppetlabs/http/client/async.clj
- src/clj/puppetlabs/http/client/common.clj
- src/java/com/puppetlabs/http/client/impl/Deliverable.java
- src/java/com/puppetlabs/http/client/impl/ExceptionInsertingPipedInputStream.java
- src/java/com/puppetlabs/http/client/impl/FnDeliverable.java
- src/java/com/puppetlabs/http/client/impl/Promise.java
- src/java/com/puppetlabs/http/client/impl/StreamingAsyncResponseConsumer.java
- test/puppetlabs/http/client/async_plaintext_test.clj
- test/puppetlabs/http/client/decompress_test.clj
Adds a new :as option that uses Apache's AsyncConsumer to return the response as quickly as possible then asynchronously stream the response body using piped input/output streams.
This is Clojure support only at the moment.
@cprice404 @rlinehan Hopefully this aligns reasonably with our discussions.
@mruzicka @dmcpl If you guys have time, I'd appreciate your comments.
Thanks!
> (PE-11976) Add option to return response early and stream body asynchronously

- project.clj
- src/clj/puppetlabs/http/client/async.clj
- test/puppetlabs/http/client/async_plaintext_test.clj
This commit updates us to the latest version of the Apache
HTTPAsyncClient.  This is necessary in order to make it
possible to use this library in the same VM as the latest
version of clj-http, because they have some common dependencies.
The commit also cleans up some other dependencies while I was
in there.
> (TK-303) Update to latest apache httpasyncclient

- .gitignore
Update .gitignore to exclude anything that starts with `.lein` (e.g.
`.lein-failures` or `.lein-repl-history`).
> (maint) Update .gitignore

- src/clj/puppetlabs/http/client/async.clj
I also added a caveat to the usage of the :stream response body so
users know the behavior isn't streaming, just returns an instance of
InputStream.
> (MAINT) Update docs to include :unbuffered-stream

- project.clj
There was a bug in the previous version of the Apache HttpAsyncClient library
that caused the cline tto hang if the process had exhausted the number of open
file descriptors it was allowed. This bug was fixed in the 4.1.2 release,
which this commit bumps to.
> (TK-308) Bump Apache HttpAsyncClient library to 4.1.2

- doc/clojure-client.md
- doc/metrics.md
- project.clj
- src/clj/puppetlabs/http/client/async.clj
- src/clj/puppetlabs/http/client/common.clj
- src/clj/puppetlabs/http/client/metrics.clj
- src/clj/puppetlabs/http/client/sync.clj
- src/java/com/puppetlabs/http/client/Async.java
- src/java/com/puppetlabs/http/client/AsyncHttpClient.java
- src/java/com/puppetlabs/http/client/ClientOptions.java
- src/java/com/puppetlabs/http/client/Sync.java
- src/java/com/puppetlabs/http/client/SyncHttpClient.java
- src/java/com/puppetlabs/http/client/impl/JavaClient.java
- src/java/com/puppetlabs/http/client/impl/PersistentAsyncHttpClient.java
- src/java/com/puppetlabs/http/client/impl/PersistentSyncHttpClient.java
- src/java/com/puppetlabs/http/client/impl/metrics/TimerUtils.java
- src/java/com/puppetlabs/http/client/metrics/Metrics.java
- test/com/puppetlabs/http/client/impl/metrics_unit_test.clj
- test/puppetlabs/http/client/metrics_test.clj
Add two new client options - `server-id` and `metric-prefix` that allow the
metric namespace to be configured rather than always
`puppetlabs.http-client.experimental`.
If `server-id` is set, the metric namespace becomes
`puppetlabs.<server-id>.http-client.experimental`.
If `metric-prefix` is set, the metric namespace becomes
`<metric-prefix>.http-client.experimental`.
If both are set, `metric-prefix` wins out and a warning message is logged.
> (TK-402) Allow metric namespace to be configurable

- .travis.yml
- project.clj
This commit migrates tk-auth to using clj-parent version 0.3.3 for its
dependencies.  This commit also updates the i18n plugin dependency from
0.4.3 to 0.6.0 for compatibility with the version of i18n being
inherited from clj-parent.  This commit also upgrades the lein version
to 2.7.1 in the .travis.yml file since 2.7.1 is the minimum version
required for compatibility with lein/clj-parent.
> (TK-430) Migrate to clj-parent 0.3.3 and bump i18n to 0.6.0

- doc/clojure-client.md
- project.clj
- src/clj/puppetlabs/http/client/async.clj
- src/clj/puppetlabs/http/client/common.clj
- src/clj/puppetlabs/http/client/sync.clj
- src/java/com/puppetlabs/http/client/CompressType.java
- src/java/com/puppetlabs/http/client/RequestOptions.java
- src/java/com/puppetlabs/http/client/SimpleRequestOptions.java
- src/java/com/puppetlabs/http/client/Sync.java
- src/java/com/puppetlabs/http/client/impl/CoercedRequestOptions.java
- src/java/com/puppetlabs/http/client/impl/JavaClient.java
- test/puppetlabs/http/client/gzip_request_test.clj
This commit adds a new Clojure HTTP request option,
:compress-request-body`, and corresponding Java option which can be used
to have gzip compression applied to the request's body before it is sent
along to the server.
> (PDB-2640) Add option for gzip compressing a request's body

- .travis.yml
- src/clj/puppetlabs/http/client/async.clj
- src/clj/puppetlabs/http/client/common.clj
- src/clj/puppetlabs/http/client/sync.clj
- src/java/com/puppetlabs/http/client/Async.java
- src/java/com/puppetlabs/http/client/ClientOptions.java
- src/java/com/puppetlabs/http/client/Sync.java
- src/java/com/puppetlabs/http/client/impl/JavaClient.java
- src/java/com/puppetlabs/http/client/impl/PersistentAsyncHttpClient.java
- src/java/com/puppetlabs/http/client/impl/PersistentSyncHttpClient.java
- src/java/com/puppetlabs/http/client/impl/metrics/TimerUtils.java
- test/com/puppetlabs/http/client/impl/metrics_unit_test.clj
- test/puppetlabs/http/client/metrics_test.clj
The primary consumer for this library (puppetserver) passes metric ids
for all metrics it's concerned about and does not need to use any of the
autogenerated url metrics.
This patch allows configuring whether or not to generate url metrics.
It parameterizes the clojure async and sync clients, and adds a
commensurate field to ClientOptions for Java clients.  The default is to
enable url metrics for compatability.
The actual functionality was plumbed by @rlinehan
> (TK-443) Allow turning off URL metrics

- project.clj
- src/clj/puppetlabs/http/client/async.clj
- src/clj/puppetlabs/http/client/common.clj
- test/puppetlabs/http/client/async_plaintext_test.clj
- test/puppetlabs/http/client/async_unbuffered_test.clj
- test/puppetlabs/http/client/sync_ssl_test.clj
Bumps clj-parent to 4.2.10
There have been issues seen with clj and java11 where clojure is unable
to find the class associated with specific java interop calls.  In this
case, the "RequestOptions" constructor was occasionally ambigous.  In
order to rectify this issue, in all places where there is some ambiguity,
type assertions are added.
In addition, there was some type issues with the common/RequestOptions
ahd how it was handled.  With the exiting code, there is one consistent
path through RequestOptions that passes a URI.  Schema type assertions
were added to demonstrate and validate the behavior, and tests were
created to demonstrate the correct handling of URL and URI types for
url specification.
> (PE-27189) disambiguate ambiguous type specifications

- src/clj/puppetlabs/http/client/async.clj
- src/clj/puppetlabs/http/client/common.clj
- src/java/com/puppetlabs/http/client/Response.java
- src/java/com/puppetlabs/http/client/impl/JavaClient.java
- src/java/com/puppetlabs/http/client/impl/JavaResponseDeliveryDelegate.java
- src/java/com/puppetlabs/http/client/impl/ResponseDeliveryDelegate.java
- test/puppetlabs/http/client/async_plaintext_test.clj
- test/puppetlabs/http/client/sync_plaintext_test.clj
This commit adds an additional field to the Response object: the status
message or reason phrase that goes along with the HTTP code. This allows
us to better match the API for Puppet's HTTP response object, for
ruby/java interop in puppetserver.
> (SERVER-2780) Add reason phrase to HTTP response

- .travis.yml
- CHANGELOG.md
- project.clj
- src/java/com/puppetlabs/http/client/ClientOptions.java
- test/puppetlabs/http/client/sync_ssl_test.clj
This updates the DEFAULT_SSL_PROTOCOLS variable to TLSv1.2 and TLSv1.3, to be in line with the desired defaults used in Puppet and PE.
The clojure sync client now throws a ConnectionClosedException, rather than an SSLException, when a connection can't be established due to no valid protocols. This happens in the latest Java 11 versions, but older Java 11 versions (e.g. 11.0.2 used by Travis) still throws an SSLHandshakeException.  This commit changes java-unsupported-protocol-exception? to be able to handle both of these cases.
Note that there still seems to be cases where ConnectionClosedException is picked up by the HttpClientException block (using the Java sync client) and some cases where it isn't (Clojure sync client).
Creating a new major since this removes TLSv1 and TLSv1.1 from …
> (PE-33177) Update ClientOptions default SSL protocols

- CHANGELOG.md
- src/clj/puppetlabs/http/client/sync.clj
Presumably from a bad copy+paste, the `options` function was previously using
the `POST` method to make requests, making it identical to the `post` function.
> (maint) Use `OPTIONS` request method when calling the sync client's `options` function

- src/java/com/puppetlabs/http/client/impl/JavaClient.java
The apache http client library has the concept of "stateless" and
"stateful" connections, where a stateful connection is one made with an
associated user identity (either NTLM or an SSL certificate). The
default implementation tracks this information (which it refers to as
the "user token") on the HTTP context and uses it to avoid reusing a
connection when the user token has changed.
Because we create a new HTTP context for every request, we don't
properly track that token, meaning each time the client tries to reuse a
connection, it finds that the token has changed (it thinks the old value
is null, the the new value is not null) and rejects the connection. This
creates a substantial performance hit in cases where we make many
requests in a row.
Because we define the SSL context at the …
> (PE-34843) Properly reuse connections with a client cert

- CHANGELOG.md
- project.clj
- src/java/com/puppetlabs/http/client/impl/JavaClient.java
- test/puppetlabs/http/client/sync_plaintext_test.clj
The design of the client does not allow multiple entries for the
same header name, as headers are returned in a map, rather than
an array of them.  As a result, headers like "Set-Cookie" would only
return the last one seen if they were encountered. This alters the
behavior to concatenate any of the "Set-Cookie" entries together,
separated by a newline character. This seems to be a fairly common
convention for clients that use headers with maps.
Tests were updated to include multiple cookies, and demonstrate
the behavior.
> (maint) add support for multiple Set-Cookie headers in a response

- CHANGELOG.md
- src/java/com/puppetlabs/http/client/impl/StreamingAsyncResponseConsumer.java
- test/puppetlabs/http/client/async_unbuffered_test.clj
In the case that an unbuffered stream is used and the server responds
in a 204, with no response, the client was throwing an exception because
the entity in the response is null. This adds a test that demonstrates
the failure, and fixes the underlying issue.
> (maint) ensure unbuffered-stream correctly handles 204 responses 
